version: "3.9"

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongodb:/data/db

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    restart: always
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra-cluster-0"
    ports:
      - 9042:9042

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: --init_file /data/mysql/init.sql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db/mysql/init.sql:/data/mysql/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nah_id_win
      
  app:
    build: .
    container_name: cassandra-vs-mongodb-benchmarks
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - mysql
      - cassandra
    environment:
      MYSQL_ROOT_PASSWORD: nah_id_win