version: "3.9"

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongodb:/data/db

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    restart: always
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra-cluster-0"
    ports:
      - 9042:9042
      
  app:
    build: .
    container_name: cassandra-vs-mongodb-benchmarks
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - cassandra